# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Tesista/Desktop/vivado projects/fix_7_novembre/fix_7_novembre.srcs/sources_1/ip/transmitter_fifo/transmitter_fifo.xci
# IP: The module: 'transmitter_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tesista/Desktop/vivado projects/fix_7_novembre/fix_7_novembre.srcs/sources_1/ip/transmitter_fifo/transmitter_fifo/transmitter_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Tesista/Desktop/vivado projects/fix_7_novembre/fix_7_novembre.srcs/sources_1/ip/transmitter_fifo/transmitter_fifo/transmitter_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Tesista/Desktop/vivado projects/fix_7_novembre/fix_7_novembre.srcs/sources_1/ip/transmitter_fifo/transmitter_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Tesista/Desktop/vivado projects/fix_7_novembre/fix_7_novembre.srcs/sources_1/ip/transmitter_fifo/transmitter_fifo.xci
# IP: The module: 'transmitter_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tesista/Desktop/vivado projects/fix_7_novembre/fix_7_novembre.srcs/sources_1/ip/transmitter_fifo/transmitter_fifo/transmitter_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Tesista/Desktop/vivado projects/fix_7_novembre/fix_7_novembre.srcs/sources_1/ip/transmitter_fifo/transmitter_fifo/transmitter_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Tesista/Desktop/vivado projects/fix_7_novembre/fix_7_novembre.srcs/sources_1/ip/transmitter_fifo/transmitter_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
