# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/receiver_FIFO/receiver_FIFO.xci
# IP: The module: 'receiver_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/receiver_FIFO/receiver_FIFO/receiver_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'receiver_FIFO'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/receiver_FIFO/receiver_FIFO/receiver_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'receiver_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/receiver_FIFO/receiver_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'receiver_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/receiver_FIFO/receiver_FIFO.xci
# IP: The module: 'receiver_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/receiver_FIFO/receiver_FIFO/receiver_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'receiver_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/receiver_FIFO/receiver_FIFO/receiver_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'receiver_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/receiver_FIFO/receiver_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'receiver_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
