# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Valerio/Desktop/TESI_DIGITALE/led_blik_artix/led_blik_artix.cache/wt [current_project]
set_property parent.project_path C:/Users/Valerio/Desktop/TESI_DIGITALE/led_blik_artix/led_blik_artix.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Valerio/Desktop/TESI_DIGITALE/led_blik_artix/led_blik_artix.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/Valerio/Desktop/TESI_DIGITALE/led_blik_artix/led_blik_artix.srcs/sources_1/new/led_blink.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Valerio/Desktop/TESI_DIGITALE/led_blik_artix/led_blik_artix.srcs/constrs_1/new/led_blink_ucf.xdc
set_property used_in_implementation false [get_files C:/Users/Valerio/Desktop/TESI_DIGITALE/led_blik_artix/led_blik_artix.srcs/constrs_1/new/led_blink_ucf.xdc]


synth_design -top led_blink -part xc7a100tcsg324-1


write_checkpoint -force -noxdef led_blink.dcp

catch { report_utilization -file led_blink_utilization_synth.rpt -pb led_blink_utilization_synth.pb }
