webtalk_init -webtalk_dir C:/Users/Valerio/Desktop/TESI_DIGITALE/king_adc/king_adc.sim/sim_2/behav/xsim.dir/simulazioneADC_BRIDGE_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Oct 02 23:14:44 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1756540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6139b961-0699-4a21-8fbc-ec3f6f3aa91c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c15dd3b4c06d45c5a6a71d572676da02" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "66" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "977680 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "9" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "42.48_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "21904_KB" -context "xsim\\usage"
webtalk_transmit -clientid 568655752 -regid "" -xml C:/Users/Valerio/Desktop/TESI_DIGITALE/king_adc/king_adc.sim/sim_2/behav/xsim.dir/simulazioneADC_BRIDGE_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Valerio/Desktop/TESI_DIGITALE/king_adc/king_adc.sim/sim_2/behav/xsim.dir/simulazioneADC_BRIDGE_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Valerio/Desktop/TESI_DIGITALE/king_adc/king_adc.sim/sim_2/behav/xsim.dir/simulazioneADC_BRIDGE_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
