# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/ftdi_clock_gen/ftdi_clock_gen.xci
# IP: The module: 'ftdi_clock_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/ftdi_clock_gen/ftdi_clock_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ftdi_clock_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/ftdi_clock_gen/ftdi_clock_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ftdi_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/ftdi_clock_gen/ftdi_clock_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ftdi_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/ftdi_clock_gen/ftdi_clock_gen.xci
# IP: The module: 'ftdi_clock_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/ftdi_clock_gen/ftdi_clock_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ftdi_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/ftdi_clock_gen/ftdi_clock_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ftdi_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/test_Ax3/test_Ax3.srcs/sources_1/ip/ftdi_clock_gen/ftdi_clock_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ftdi_clock_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
