# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Valerio/Desktop/TESI_DIGITALE/axel_adc_bridge/axel_adc_bridge.srcs/sources_1/ip/clock_generator/clock_generator.xci
# IP: The module: 'clock_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/axel_adc_bridge/axel_adc_bridge.srcs/sources_1/ip/clock_generator/clock_generator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_generator'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/axel_adc_bridge/axel_adc_bridge.srcs/sources_1/ip/clock_generator/clock_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/axel_adc_bridge/axel_adc_bridge.srcs/sources_1/ip/clock_generator/clock_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/Valerio/Desktop/TESI_DIGITALE/axel_adc_bridge/axel_adc_bridge.srcs/sources_1/ip/clock_generator/clock_generator.xci
# IP: The module: 'clock_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/axel_adc_bridge/axel_adc_bridge.srcs/sources_1/ip/clock_generator/clock_generator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/axel_adc_bridge/axel_adc_bridge.srcs/sources_1/ip/clock_generator/clock_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Valerio/Desktop/TESI_DIGITALE/axel_adc_bridge/axel_adc_bridge.srcs/sources_1/ip/clock_generator/clock_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
