set_property SRC_FILE_INFO {cfile:C:/Users/Valerio/Desktop/TESI_DIGITALE/led_blik_artix/led_blik_artix.srcs/constrs_1/new/led_blink_ucf.xdc rfile:../../../led_blik_artix.srcs/constrs_1/new/led_blink_ucf.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports led_1]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M16 [get_ports led_2]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports button_1]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1 [get_ports button_2]
